### ISSUE TITLE
How i run this project in linux

### ISSUE THREAD

**Issue by V3ct0r** [Netcode-Hub/DemoBlazorCRUDOperationsWithDotNet8#1]
i use de command 
```shell
dotnet watch
``` 
i have the error

```shell
No se encontró ningún archivo del proyecto MSBuild en "/home/hector/proyectos/dotnet/DemoBlazorCRUDOperationsWithDotNet8". Especifique qué proyecto debe utilizarse con la opción --project.
```

**Comment by Netcode-Hub** [comment]
Sorry , I don’t understand the language

**Comment by V3ct0r** [comment]
OK thanks

**Comment by Netcode-Hub** [comment]
Would be a bale to assist you if you can change the error language to
English

**Comment by V3ct0r** [comment]
`No MSBuild project file found in "/home/hector/projects/dotnet/DemoBlazorCRUDOperationsWithDotNet8". Specify which project should be used with the --project option.`

**Comment by Netcode-Hub** [comment]
Set Infrastructure as default project and API as startup project if using
clean architecture. Else set ApI as startup project and default project at
the console.
